### PR TITLE
Content feed

### LINKED ISSUE #34: Combine frontpage new bots/bot updates feed into a general activity feed

### PR DESCRIPTION
**Pull request by Mimz3598**
Merged Recently updated bots feed with New bots into new Activity feed with news(Issue 34 and 35). 

New model News was created with date of creation, title, text and optional youtube link. Index.html was changed and in views.py in class Index, there is management of new bots, recent updated bots and news - theese three lists are merged, sorted and sent to template.

Admins are able to create new object in admin site in Newss section - title and youtube link are optional. There should be no need for reformating yt link, it's done during saving object to database. Valid youtube link contains https://www.

This pull request closes #34 and #35

### CODE REVIEW

**Comment by lladdy** [comment]
Fantastic. Thanks so much @Mimz3598. I will review and provide feedback when I get some spare time. :)

**Comment by lladdy** [comment]
@Mimz3598 
This is looking really great. The embed is a great idea for the yt link and I think will draw a lot of attention to our community streams.

I get an error on submission if I put another link (e.g. https://github.com/) in the yt link section.
Are you able to throw a validation error if it doesn't appear to be a valid youtube link?

I really like the slider functionality, but I'm wondering whether it's more practical to avoid requiring the user to click to see the extra content.
The original idea in my head was a little bit like a facebook feed (see a rough mockup below). With that said, I have little problem merging it like it is - it looks great.
Let me know your thoughts :)

Rough mockup:
image

**Comment by Mimz3598** [comment]
I don't have any problems with your suggestion, just want to ask, if there are many updates of bots or creation of new ones, won't be the activity feed full of this information and youtube videos, for example, will be pushed down? I am not sure, if you understand my concern - all the activity will be full of updates or creations instead of something, that should be visible as first. Because of this i think table with 5 most recent changes is good, but what do you think?

**Comment by Mimz3598** [comment]
Or i can do it your way, but still show top 5 recent updates and creations of bots, to not overflow activity feed with this information? What do you say?

**Comment by lladdy** [comment]
@Mimz3598 
> won't be the activity feed full of this information and youtube videos, for example, will be pushed down?
I think this is a valid concern and I'm glad you mentioned it.

> but still show top 5 recent updates and creations of bots
I think I prefer this - combine these 2 events into 1 list and have a separate one for "news".

**Comment by Mimz3598** [comment]
So, to make sure we understand each other - there will be Activity feed with news and 10 bot informations(5 updated and 5 new ones). In other words i will use your mockup, but show only recent bot operations. Correct?

**Comment by Mimz3598** [comment]
I updated project, hope you will like it.

**Comment by lladdy** [comment]
Great work @Mimz3598! I'll probably continue to tweak it as things change but that'll be super simple since you've done the hard work - thanks 👍 
I'm also going to try to find a place to use the slider you created. I thought it looked quite good.

**Pull request merged**
