### PR TITLE
Stats generator

### PR DESCRIPTION
**Pull request by eladyaniv01**
- After adding the `str` methods for better readability it is quite clear that the season is not consistent,  

- A solution to this problem is suggested in https://github.com/aiarena/aiarena-web/pull/54
- I honestly do not know how to avoid a refactor and just fix the stat generator,  the model relationship logic is flawed and needs to be re designed. 

### Running this code in dev env will show that seasons are not filtered properly when calculating matchups 
```python
from aiarena.core.models import Bot, SeasonParticipation, SeasonBotMatchupStats, Season
bot = Bot.objects.first()
sp = bot.seasonparticipation_set.all()[0]
for mu in sp.season_matchup_stats.all():
...     print(mu)
...     print(mu.bot)
...     
Season 1 devadmin_bot1 VS Season 1 devadmin_bot2
Season 1 devadmin_bot1
Season 1 devadmin_bot1 VS Season 1 devuser1_bot1
Season 1 devadmin_bot1
Season 1 devadmin_bot1 VS Season 1 devuser1_bot2
Season 1 devadmin_bot1
Season 1 devadmin_bot1 VS Season 1 devuser2_bot1
Season 1 devadmin_bot1
Season 1 devadmin_bot1 VS Season 1 devuser2_bot2
Season 1 devadmin_bot1
Season 1 devadmin_bot1 VS Season 1 devuser3_bot1
Season 1 devadmin_bot1
Season 1 devadmin_bot1 VS Season 1 devuser4_bot1
Season 1 devadmin_bot1
Season 1 devadmin_bot1 VS Season 1 devuser5_bot1
Season 1 devadmin_bot1
Season 1 devadmin_bot1 VS Season 2 devadmin_bot2
Season 1 devadmin_bot1
Season 1 devadmin_bot1 VS Season 2 devadmin_bot3
Season 1 devadmin_bot1
Season 1 devadmin_bot1 VS Season 2 devuser1_bot1
Season 1 devadmin_bot1
Season 1 devadmin_bot1 VS Season 2 devuser1_bot2
Season 1 devadmin_bot1
Season 1 devadmin_bot1 VS Season 2 devuser1_bot3
Season 1 devadmin_bot1
Season 1 devadmin_bot1 VS Season 2 devuser2_bot1
Season 1 devadmin_bot1
Season 1 devadmin_bot1 VS Season 2 devuser2_bot2
Season 1 devadmin_bot1
Season 1 devadmin_bot1 VS Season 2 devuser2_bot3
Season 1 devadmin_bot1
Season 1 devadmin_bot1 VS Season 2 devuser3_bot1
Season 1 devadmin_bot1
Season 1 devadmin_bot1 VS Season 2 devuser4_bot1
Season 1 devadmin_bot1
Season 1 devadmin_bot1 VS Season 2 devuser5_bot1
Season 1 devadmin_bot1
```

### CODE REVIEW

**Comment by lladdy** [comment]
> seasons are not filtered properly when calculating matchups
Are you referring to when the match queue is generated?

**Comment by eladyaniv01** [comment]
> > seasons are not filtered properly when calculating matchups
> 
> @eladyaniv01 Are you referring to when the match queue is generated?

I am not sure i follow, 
The  code above is produced after all results have been submitted

**Comment by lladdy** [comment]
> 
> 
> > > seasons are not filtered properly when calculating matchups
> > 
> > 
> > @eladyaniv01 Are you referring to when the match queue is generated?
> 
> I am not sure i follow,
> The code above is produced after all results have been submitted

I'm guessing "when calculating matchups" is talking about the stats generation, specifically?

**Comment by eladyaniv01** [comment]
> > > > seasons are not filtered properly when calculating matchups
> > > 
> > > 
> > > @eladyaniv01 Are you referring to when the match queue is generated?
> > 
> > 
> > I am not sure i follow,
> > The code above is produced after all results have been submitted
> 
> I'm guessing "when calculating matchups" is talking about the stats generation, specifically?

I am referring to the `SeasonMatchUpStats`  Model that is being used during stats generation but is already calculated (populated)  at that point

**Comment by lladdy** [comment]
I think currently the stats gen job deletes those and then recalculates them.

> Running this code in dev env will show that seasons are not filtered properly when calculating matchups
So it sounds like maybe we can fix this by filtering properly?

**Comment by lladdy** [comment]
@eladyaniv01 this is looking good - well done.
Can you please separate this into 2 PRs:
1) Strictly the only change(s) required to fix the stats gen season filtering.
2) Other enhancements you'd like to add.
This will make it simpler to test as I can merge in PR#1 and then PR#2 after testing #1 in isolation.

**Pull request merged**
