### PR TITLE
List requested matches for bot authors in their profile page and allow cancellations

### PR DESCRIPTION
**Pull request by Immodal**
#87 and #138 

- Requested matches appear on User Profile.
- User can cancel matches requested by them from their profile page.
- Only matches that haven't been assigned to an arena client can be cancelled.
- On success or failure, a message will display at the top of the page.
- Right now only matches cancelled by them will refund their match requests.

@lladdy @eladyaniv01 
I'm not sure if the way I implemented it is the best way to do it, do let me know if you can think of how to improve it.

image

### CODE REVIEW

**Comment by eladyaniv01** [comment]
Looking good @Immodal,
could you please add a simple unit test that ensures that this functionality is working

**Comment by lladdy** [comment]
> 
> 
> Looking good @Immodal,
> could you please add a simple unit test that ensures that this functionality is working

@Immodal check out the frontend tests. They basically just do a GET for most pages to make sure they're not broken.
If there's not one there for the profile page, you could add it. You might need to create some requested matches in the setup for the test.

**Comment by Immodal** [comment]
Given the profile test already exists, I just added the match requests to the mixin. Hopefully I put it in the right spot.

I'm actually having some trouble running tests offline. When I try to run tests I get this error and I have no idea where to look to resolve this.
```
(python_env) PS C:\Users\Nigel\Desktop\Coding\aiarena-web> python manage.py test
Creating test database for alias 'default'...
Got an error creating the test database: (1044, "Access denied for user 'aiarena'@'%' to database 'test_aiarena'")
```

**Comment by eladyaniv01** [comment]
> Given the profile test already exists, I just added the match requests to the mixin. Hopefully I put it in the right spot.
> 
> I'm actually having some trouble running tests offline. When I try to run tests I get this error and I have no idea where to look to resolve this.
> 
> ```
> (python_env) PS C:\Users\Nigel\Desktop\Coding\aiarena-web> python manage.py test
> Creating test database for alias 'default'...
> Got an error creating the test database: (1044, "Access denied for user 'aiarena'@'%' to database 'test_aiarena'")
> ```

try running this sql query
```
drop database aiarena;
create database aiarena;
drop database test_aiarena;
create database test_aiarena;
GRANT ALL PRIVILEGES ON aiarena.* TO 'aiarena'@'%';
GRANT ALL PRIVILEGES ON test_aiarena.* TO 'aiarena'@'%';```

then run `python manage.py seed`  (this is just to make sure the db was refreshed properly) 
and you should be set up

**Pull request merged**
